module.exports = {
  "workbench.colorTheme": "dislexic",
  "workbench.colorCustomizations": {
    "[dislexic]": {
      "tab.activeBackground": "#cadeef",
      "tab.inactiveBackground": "#ebf2f8",
      "breadcrumb.background": "#d2e6f3",
      "breadcrumb.foreground": "#557",
      "editor.background": "#e9f4fa",
      "editorGutter.background": "#ebf2f8",
      "activityBarBadge.background": "#4392c3",
      "sideBar.foreground": "#ebf2f8",
      "sideBarSectionHeader.background": "#4392c3",
      "button.background": "#4392c3",
      "panel.background": "#d2e6f3",
      "panelTitle.activeForeground": "#000",
      "panelTitle.inactiveForeground": "#668",
      "terminal.background": "#ebf2f8",
      "terminal.ansiBrightGreen": "#439D4D",
      "terminal.ansiGreen": "#31863b",
      "statusBar.background": "#4392c3",
      "gitDecoration.untrackedResourceForeground": "#439D4D",
      "gitDecoration.modifiedResourceForeground": "#e47b02",
      "gitDecoration.deletedResourceForeground": "#e8426e",
      "gitDecoration.addedResourceForeground": "#439D4D",
      "gitDecoration.stageModifiedResourceForeground": "#e47b02",
      "gitDecoration.stageDeletedResourceForeground": "#e8426e",
      "diffEditor.insertedTextBackground": "#99b76d23",
      "diffEditor.removedTextBackground": "#ef535033",
    }
  },
  "cSpell.allowCompoundWords": true,
  "cSpell.enabled": true,
  "workbench.iconTheme": "vscode-icons",
  "window.zoomLevel": 1.5,
  "editor.lineHeight": 25,
  "editor.fontSize": 16,
  "editor.letterSpacing": 0,
  "terminal.integrated.fontSize": 16,
  "editor.fontFamily": "OpenDyslexicMono-Regular, 'Courier New', monospace",
  "editor.minimap.enabled": false,
  "editor.renderWhitespace": "none",
  "editor.renderControlCharacters": false,
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": "active"
}
